spring.application.name=real-time-order-processing

spring.datasource.url=jdbc:postgresql://localhost:5432/real_time_order_processing
spring.datasource.username=postgres
spring.datasource.password=Devesh@7113